// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module encrypt (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        statemt_0_address0,
        statemt_0_ce0,
        statemt_0_we0,
        statemt_0_d0,
        statemt_0_q0,
        statemt_0_address1,
        statemt_0_ce1,
        statemt_0_we1,
        statemt_0_d1,
        statemt_0_q1,
        statemt_1_address0,
        statemt_1_ce0,
        statemt_1_we0,
        statemt_1_d0,
        statemt_1_q0,
        statemt_1_address1,
        statemt_1_ce1,
        statemt_1_we1,
        statemt_1_d1,
        statemt_1_q1,
        key_0_address0,
        key_0_ce0,
        key_0_q0,
        word_1_address0,
        word_1_ce0,
        word_1_we0,
        word_1_d0,
        word_1_q0,
        word_1_address1,
        word_1_ce1,
        word_1_q1,
        word_0_address0,
        word_0_ce0,
        word_0_we0,
        word_0_d0,
        word_0_q0,
        word_0_address1,
        word_0_ce1,
        word_0_q1,
        round_val,
        round_val_ap_vld,
        main_result_i,
        main_result_o,
        main_result_o_ap_vld
);

parameter    ap_ST_fsm_state1 = 38'd1;
parameter    ap_ST_fsm_state2 = 38'd2;
parameter    ap_ST_fsm_state3 = 38'd4;
parameter    ap_ST_fsm_state4 = 38'd8;
parameter    ap_ST_fsm_state5 = 38'd16;
parameter    ap_ST_fsm_state6 = 38'd32;
parameter    ap_ST_fsm_state7 = 38'd64;
parameter    ap_ST_fsm_state8 = 38'd128;
parameter    ap_ST_fsm_state9 = 38'd256;
parameter    ap_ST_fsm_state10 = 38'd512;
parameter    ap_ST_fsm_state11 = 38'd1024;
parameter    ap_ST_fsm_state12 = 38'd2048;
parameter    ap_ST_fsm_state13 = 38'd4096;
parameter    ap_ST_fsm_state14 = 38'd8192;
parameter    ap_ST_fsm_state15 = 38'd16384;
parameter    ap_ST_fsm_state16 = 38'd32768;
parameter    ap_ST_fsm_state17 = 38'd65536;
parameter    ap_ST_fsm_state18 = 38'd131072;
parameter    ap_ST_fsm_state19 = 38'd262144;
parameter    ap_ST_fsm_state20 = 38'd524288;
parameter    ap_ST_fsm_state21 = 38'd1048576;
parameter    ap_ST_fsm_state22 = 38'd2097152;
parameter    ap_ST_fsm_state23 = 38'd4194304;
parameter    ap_ST_fsm_state24 = 38'd8388608;
parameter    ap_ST_fsm_state25 = 38'd16777216;
parameter    ap_ST_fsm_state26 = 38'd33554432;
parameter    ap_ST_fsm_state27 = 38'd67108864;
parameter    ap_ST_fsm_state28 = 38'd134217728;
parameter    ap_ST_fsm_state29 = 38'd268435456;
parameter    ap_ST_fsm_state30 = 38'd536870912;
parameter    ap_ST_fsm_state31 = 38'd1073741824;
parameter    ap_ST_fsm_state32 = 38'd2147483648;
parameter    ap_ST_fsm_state33 = 38'd4294967296;
parameter    ap_ST_fsm_state34 = 38'd8589934592;
parameter    ap_ST_fsm_state35 = 38'd17179869184;
parameter    ap_ST_fsm_state36 = 38'd34359738368;
parameter    ap_ST_fsm_state37 = 38'd68719476736;
parameter    ap_ST_fsm_state38 = 38'd137438953472;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] statemt_0_address0;
output   statemt_0_ce0;
output   statemt_0_we0;
output  [31:0] statemt_0_d0;
input  [31:0] statemt_0_q0;
output  [3:0] statemt_0_address1;
output   statemt_0_ce1;
output   statemt_0_we1;
output  [31:0] statemt_0_d1;
input  [31:0] statemt_0_q1;
output  [3:0] statemt_1_address0;
output   statemt_1_ce0;
output   statemt_1_we0;
output  [31:0] statemt_1_d0;
input  [31:0] statemt_1_q0;
output  [3:0] statemt_1_address1;
output   statemt_1_ce1;
output   statemt_1_we1;
output  [31:0] statemt_1_d1;
input  [31:0] statemt_1_q1;
output  [3:0] key_0_address0;
output   key_0_ce0;
input  [31:0] key_0_q0;
output  [7:0] word_1_address0;
output   word_1_ce0;
output   word_1_we0;
output  [31:0] word_1_d0;
input  [31:0] word_1_q0;
output  [7:0] word_1_address1;
output   word_1_ce1;
input  [31:0] word_1_q1;
output  [7:0] word_0_address0;
output   word_0_ce0;
output   word_0_we0;
output  [31:0] word_0_d0;
input  [31:0] word_0_q0;
output  [7:0] word_0_address1;
output   word_0_ce1;
input  [31:0] word_0_q1;
output  [4:0] round_val;
output   round_val_ap_vld;
input  [31:0] main_result_i;
output  [31:0] main_result_o;
output   main_result_o_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[3:0] statemt_0_address0;
reg statemt_0_ce0;
reg statemt_0_we0;
reg[31:0] statemt_0_d0;
reg[3:0] statemt_0_address1;
reg statemt_0_ce1;
reg statemt_0_we1;
reg[31:0] statemt_0_d1;
reg[3:0] statemt_1_address0;
reg statemt_1_ce0;
reg statemt_1_we0;
reg[31:0] statemt_1_d0;
reg[3:0] statemt_1_address1;
reg statemt_1_ce1;
reg statemt_1_we1;
reg[31:0] statemt_1_d1;
reg key_0_ce0;
reg[7:0] word_1_address0;
reg word_1_ce0;
reg word_1_we0;
reg[31:0] word_1_d0;
reg[7:0] word_1_address1;
reg word_1_ce1;
reg[7:0] word_0_address0;
reg word_0_ce0;
reg word_0_we0;
reg[31:0] word_0_d0;
reg[7:0] word_0_address1;
reg word_0_ce1;
reg round_val_ap_vld;
reg[31:0] main_result_o;
reg main_result_o_ap_vld;

(* fsm_encoding = "none" *) reg   [37:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [7:0] Sbox_address0;
reg    Sbox_ce0;
wire   [7:0] Sbox_q0;
reg   [7:0] Sbox_address1;
reg    Sbox_ce1;
wire   [7:0] Sbox_q1;
reg   [7:0] Sbox_address2;
reg    Sbox_ce2;
wire   [7:0] Sbox_q2;
reg   [7:0] Sbox_address3;
reg    Sbox_ce3;
wire   [7:0] Sbox_q3;
wire   [4:0] Rcon0_address0;
reg    Rcon0_ce0;
wire   [7:0] Rcon0_q0;
wire   [3:0] out_enc_statemt_address0;
reg    out_enc_statemt_ce0;
wire   [7:0] out_enc_statemt_q0;
reg   [7:0] reg_1267;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state29;
wire    ap_CS_fsm_state32;
reg   [7:0] reg_1271;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state31;
reg   [7:0] reg_1276;
reg   [7:0] reg_1281;
reg   [7:0] reg_1286;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state30;
reg   [7:0] reg_1291;
reg   [7:0] reg_1295;
reg   [7:0] reg_1299;
wire   [2:0] j_fu_1309_p2;
reg   [2:0] j_reg_3155;
wire    ap_CS_fsm_state2;
wire   [3:0] shl_ln_fu_1319_p3;
reg   [3:0] shl_ln_reg_3160;
wire   [0:0] icmp_ln137_fu_1303_p2;
wire   [2:0] i_fu_1333_p2;
reg   [2:0] i_reg_3168;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln140_fu_1327_p2;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln146_fu_1431_p2;
wire    ap_CS_fsm_state6;
reg   [31:0] word_1_load_8_reg_3229;
wire    ap_CS_fsm_state7;
reg   [0:0] tmp_7_reg_3235;
wire   [3:0] trunc_ln248_1_fu_1495_p1;
reg   [3:0] trunc_ln248_1_reg_3241;
reg   [5:0] zext_ln_reg_3246;
reg   [31:0] word_0_load_7_reg_3251;
reg   [0:0] tmp_11_reg_3257;
wire   [3:0] trunc_ln248_3_fu_1523_p1;
reg   [3:0] trunc_ln248_3_reg_3263;
reg   [5:0] zext_ln248_2_reg_3268;
reg   [31:0] word_1_load_9_reg_3273;
reg   [0:0] tmp_15_reg_3279;
wire   [3:0] trunc_ln248_5_fu_1551_p1;
reg   [3:0] trunc_ln248_5_reg_3285;
reg   [5:0] zext_ln248_4_reg_3290;
reg   [31:0] word_0_load_8_reg_3295;
reg   [0:0] tmp_19_reg_3301;
wire   [3:0] trunc_ln248_7_fu_1579_p1;
reg   [3:0] trunc_ln248_7_reg_3307;
reg   [5:0] zext_ln248_6_reg_3312;
wire    ap_CS_fsm_state8;
wire   [31:0] zext_ln154_2_fu_1904_p1;
wire    ap_CS_fsm_state9;
wire   [31:0] zext_ln248_fu_1908_p1;
wire   [31:0] zext_ln248_1_fu_1912_p1;
wire   [31:0] zext_ln248_3_fu_1916_p1;
wire   [8:0] zext_ln173_fu_1926_p1;
reg   [8:0] zext_ln173_reg_3362;
wire    ap_CS_fsm_state10;
wire   [8:0] zext_ln172_fu_1930_p1;
reg   [8:0] zext_ln172_reg_3367;
wire   [2:0] i_1_fu_1940_p2;
reg   [2:0] i_1_reg_3375;
wire    ap_CS_fsm_state11;
wire   [0:0] trunc_ln173_fu_1946_p1;
reg   [0:0] trunc_ln173_reg_3380;
wire   [0:0] icmp_ln172_fu_1934_p2;
wire   [8:0] add_ln173_2_fu_1997_p2;
reg   [8:0] add_ln173_2_reg_3390;
wire   [31:0] select_ln173_3_fu_2026_p3;
reg   [31:0] select_ln173_3_reg_3400;
wire   [5:0] j_2_fu_2034_p2;
wire   [2:0] j_1_fu_2065_p2;
reg   [2:0] j_1_reg_3413;
wire    ap_CS_fsm_state13;
wire   [0:0] icmp_ln565_fu_2059_p2;
reg   [3:0] statemt_0_addr_reg_3438;
reg   [3:0] statemt_1_addr_reg_3443;
reg   [3:0] statemt_0_addr_1_reg_3448;
reg   [3:0] statemt_1_addr_1_reg_3453;
wire    ap_CS_fsm_state16;
wire   [31:0] zext_ln393_2_fu_2285_p1;
reg   [31:0] zext_ln393_2_reg_3616;
wire    ap_CS_fsm_state22;
wire   [2:0] j_4_fu_2299_p2;
reg   [2:0] j_4_reg_3624;
wire    ap_CS_fsm_state23;
wire   [63:0] zext_ln384_fu_2311_p1;
reg   [63:0] zext_ln384_reg_3629;
wire   [0:0] icmp_ln380_fu_2293_p2;
wire   [63:0] zext_ln393_fu_2323_p1;
reg   [63:0] zext_ln393_reg_3645;
wire   [31:0] xor_ln393_2_fu_2468_p2;
reg   [31:0] xor_ln393_2_reg_3681;
wire    ap_CS_fsm_state24;
wire   [31:0] xor_ln405_2_fu_2580_p2;
reg   [31:0] xor_ln405_2_reg_3686;
wire   [31:0] xor_ln417_2_fu_2692_p2;
reg   [31:0] xor_ln417_2_reg_3691;
wire   [31:0] xor_ln429_2_fu_2798_p2;
reg   [31:0] xor_ln429_2_reg_3696;
wire   [2:0] j_5_fu_2810_p2;
reg   [2:0] j_5_reg_3704;
wire    ap_CS_fsm_state26;
wire   [63:0] zext_ln437_fu_2822_p1;
reg   [63:0] zext_ln437_reg_3709;
wire   [0:0] icmp_ln433_fu_2804_p2;
wire   [63:0] zext_ln439_fu_2834_p1;
reg   [63:0] zext_ln439_reg_3725;
wire   [3:0] i_4_fu_2840_p2;
wire    ap_CS_fsm_state28;
wire   [2:0] j_3_fu_3012_p2;
reg   [2:0] j_3_reg_3829;
wire    ap_CS_fsm_state35;
wire   [0:0] icmp_ln565_1_fu_3006_p2;
reg   [3:0] statemt_0_addr_10_reg_3854;
reg   [3:0] statemt_1_addr_10_reg_3859;
reg   [3:0] statemt_0_addr_11_reg_3864;
reg   [3:0] statemt_1_addr_11_reg_3869;
wire   [4:0] i_3_fu_3078_p2;
reg   [4:0] i_3_reg_3877;
wire    ap_CS_fsm_state37;
wire   [0:0] icmp_ln139_fu_3072_p2;
reg   [3:0] ret_0_address0;
reg    ret_0_ce0;
reg    ret_0_we0;
wire   [31:0] ret_0_q0;
reg   [3:0] ret_0_address1;
reg    ret_0_ce1;
reg    ret_0_we1;
wire   [31:0] ret_0_q1;
reg   [3:0] ret_1_address0;
reg    ret_1_ce0;
reg    ret_1_we0;
wire   [31:0] ret_1_q0;
reg   [3:0] ret_1_address1;
reg    ret_1_ce1;
reg    ret_1_we1;
wire   [31:0] ret_1_q1;
reg   [2:0] j_0_i_reg_1084;
reg   [2:0] i_0_i_reg_1096;
wire    ap_CS_fsm_state4;
reg   [5:0] j_1_i_reg_1108;
reg   [31:0] temp_1335_0_0_reg_1120;
reg   [31:0] temp_0_1_0_reg_1130;
reg   [31:0] temp_0_0_0_reg_1140;
reg   [31:0] temp_1_1_reg_1150;
reg   [2:0] i_2_i_reg_1160;
wire    ap_CS_fsm_state12;
reg   [2:0] j_0_i7_reg_1171;
wire    ap_CS_fsm_state14;
reg   [3:0] n_assign_reg_1182;
reg   [2:0] j_0_i14_reg_1194;
wire    ap_CS_fsm_state25;
reg   [2:0] j_1_i19_reg_1205;
wire    ap_CS_fsm_state27;
reg   [2:0] j_0_i24_reg_1216;
wire    ap_CS_fsm_state34;
wire    ap_CS_fsm_state36;
reg   [4:0] i_2_reg_1227;
wire    ap_CS_fsm_state38;
wire   [63:0] zext_ln142_1_fu_1348_p1;
wire  signed [63:0] sext_ln142_2_fu_1425_p1;
wire   [63:0] zext_ln155_1_fu_1469_p1;
wire   [63:0] zext_ln154_fu_1453_p1;
wire  signed [63:0] sext_ln248_fu_1659_p1;
wire   [63:0] zext_ln154_1_fu_1680_p1;
wire  signed [63:0] sext_ln248_1_fu_1751_p1;
wire  signed [63:0] sext_ln248_2_fu_1822_p1;
wire  signed [63:0] sext_ln248_3_fu_1893_p1;
wire  signed [63:0] sext_ln173_fu_1991_p1;
wire  signed [63:0] sext_ln173_1_fu_2040_p1;
wire   [63:0] zext_ln570_fu_2071_p1;
wire   [63:0] tmp_s_fu_2077_p3;
wire   [63:0] zext_ln570_1_fu_2093_p1;
wire   [63:0] zext_ln572_fu_2105_p1;
wire  signed [63:0] sext_ln140_1_fu_2117_p1;
wire  signed [63:0] sext_ln141_1_fu_2122_p1;
wire  signed [63:0] sext_ln146_1_fu_2127_p1;
wire  signed [63:0] sext_ln147_1_fu_2132_p1;
wire  signed [63:0] sext_ln142_1_fu_2137_p1;
wire  signed [63:0] sext_ln143_1_fu_2142_p1;
wire  signed [63:0] sext_ln149_1_fu_2147_p1;
wire  signed [63:0] sext_ln150_1_fu_2152_p1;
wire  signed [63:0] sext_ln153_1_fu_2157_p1;
wire  signed [63:0] sext_ln154_1_fu_2162_p1;
wire  signed [63:0] sext_ln159_1_fu_2167_p1;
wire  signed [63:0] sext_ln160_1_fu_2172_p1;
wire  signed [63:0] sext_ln155_1_fu_2197_p1;
wire  signed [63:0] sext_ln156_1_fu_2202_p1;
wire  signed [63:0] sext_ln161_1_fu_2207_p1;
wire  signed [63:0] sext_ln162_1_fu_2212_p1;
wire   [63:0] zext_ln393_1_fu_2334_p1;
wire   [63:0] zext_ln417_fu_2350_p1;
wire  signed [63:0] sext_ln140_fu_2846_p1;
wire  signed [63:0] sext_ln141_fu_2851_p1;
wire  signed [63:0] sext_ln146_fu_2856_p1;
wire  signed [63:0] sext_ln147_fu_2861_p1;
wire  signed [63:0] sext_ln142_fu_2866_p1;
wire  signed [63:0] sext_ln143_fu_2871_p1;
wire  signed [63:0] sext_ln149_fu_2876_p1;
wire  signed [63:0] sext_ln150_fu_2881_p1;
wire  signed [63:0] sext_ln153_fu_2886_p1;
wire  signed [63:0] sext_ln154_fu_2891_p1;
wire  signed [63:0] sext_ln159_fu_2896_p1;
wire  signed [63:0] sext_ln160_fu_2901_p1;
wire  signed [63:0] sext_ln155_fu_2926_p1;
wire  signed [63:0] sext_ln156_fu_2931_p1;
wire  signed [63:0] sext_ln161_fu_2936_p1;
wire  signed [63:0] sext_ln162_fu_2941_p1;
wire   [63:0] zext_ln570_3_fu_3026_p1;
wire   [63:0] zext_ln572_2_fu_3042_p1;
wire   [63:0] zext_ln570_2_fu_3054_p1;
wire   [63:0] zext_ln572_1_fu_3066_p1;
wire   [63:0] zext_ln141_1_fu_3099_p1;
wire   [63:0] zext_ln141_fu_3084_p1;
wire   [31:0] add_ln141_fu_3135_p2;
wire   [0:0] trunc_ln142_1_fu_1353_p1;
wire   [0:0] icmp_ln152_fu_1441_p2;
wire   [31:0] xor_ln173_fu_2052_p2;
wire   [31:0] grp_fu_1239_p2;
wire   [31:0] grp_fu_1253_p2;
wire    ap_CS_fsm_state15;
wire   [0:0] icmp_ln112_fu_2111_p2;
wire   [31:0] zext_ln147_1_fu_2192_p1;
wire   [31:0] zext_ln146_1_fu_2187_p1;
wire   [31:0] zext_ln150_1_fu_2232_p1;
wire   [31:0] zext_ln149_1_fu_2227_p1;
wire    ap_CS_fsm_state21;
wire   [31:0] zext_ln159_1_fu_2247_p1;
wire   [31:0] zext_ln160_1_fu_2252_p1;
wire   [31:0] zext_ln161_1_fu_2267_p1;
wire   [31:0] zext_ln162_1_fu_2272_p1;
wire   [31:0] zext_ln147_fu_2921_p1;
wire   [31:0] zext_ln146_fu_2916_p1;
wire   [31:0] zext_ln150_fu_2961_p1;
wire   [31:0] zext_ln149_fu_2956_p1;
wire    ap_CS_fsm_state33;
wire   [31:0] zext_ln159_fu_2976_p1;
wire   [31:0] zext_ln160_fu_2981_p1;
wire   [31:0] zext_ln161_fu_2996_p1;
wire   [31:0] zext_ln162_fu_3001_p1;
wire   [31:0] grp_fu_1246_p2;
wire   [31:0] grp_fu_1260_p2;
wire   [31:0] zext_ln141_5_fu_2177_p1;
wire   [31:0] zext_ln142_5_fu_2182_p1;
wire   [31:0] zext_ln143_1_fu_2222_p1;
wire   [31:0] zext_ln140_1_fu_2217_p1;
wire   [31:0] zext_ln154_4_fu_2237_p1;
wire   [31:0] zext_ln155_3_fu_2242_p1;
wire   [31:0] zext_ln156_1_fu_2262_p1;
wire   [31:0] zext_ln153_1_fu_2257_p1;
wire   [31:0] zext_ln141_4_fu_2906_p1;
wire   [31:0] zext_ln142_4_fu_2911_p1;
wire   [31:0] zext_ln143_fu_2951_p1;
wire   [31:0] zext_ln140_fu_2946_p1;
wire   [31:0] zext_ln154_3_fu_2966_p1;
wire   [31:0] zext_ln155_2_fu_2971_p1;
wire   [31:0] zext_ln156_fu_2991_p1;
wire   [31:0] zext_ln153_fu_2986_p1;
wire   [1:0] trunc_ln142_fu_1315_p1;
wire   [3:0] zext_ln142_fu_1339_p1;
wire   [3:0] add_ln142_fu_1343_p2;
wire   [1:0] lshr_ln_fu_1357_p4;
wire   [8:0] tmp_4_fu_1367_p3;
wire   [4:0] tmp_5_fu_1379_p3;
wire   [9:0] zext_ln142_2_fu_1375_p1;
wire   [9:0] zext_ln142_3_fu_1387_p1;
wire   [9:0] sub_ln142_fu_1391_p2;
wire   [2:0] trunc_ln142_2_fu_1397_p1;
wire   [6:0] tmp_3_fu_1407_p4;
wire   [2:0] or_ln142_fu_1401_p2;
wire   [9:0] tmp_6_fu_1417_p3;
wire   [1:0] trunc_ln146_fu_1437_p1;
wire   [5:0] add_ln154_fu_1447_p2;
wire   [7:0] zext_ln155_fu_1459_p1;
wire   [7:0] add_ln155_fu_1463_p2;
wire   [31:0] sub_ln248_fu_1489_p2;
wire   [31:0] sub_ln248_4_fu_1517_p2;
wire   [31:0] sub_ln248_8_fu_1545_p2;
wire   [31:0] sub_ln248_10_fu_1573_p2;
wire   [9:0] tmp_8_fu_1596_p3;
wire   [3:0] trunc_ln248_fu_1593_p1;
wire   [9:0] sub_ln248_2_fu_1603_p2;
wire   [9:0] tmp_9_fu_1609_p3;
wire   [5:0] sub_ln248_1_fu_1624_p2;
wire   [5:0] tmp_10_fu_1629_p4;
wire   [5:0] select_ln248_1_fu_1638_p3;
wire   [9:0] sext_ln248_1_cast_fu_1645_p3;
wire   [9:0] select_ln248_fu_1617_p3;
wire   [9:0] add_ln248_fu_1653_p2;
wire   [3:0] trunc_ln154_1_fu_1664_p4;
wire   [3:0] add_ln154_1_fu_1674_p2;
wire   [9:0] tmp_12_fu_1688_p3;
wire   [3:0] trunc_ln248_2_fu_1685_p1;
wire   [9:0] sub_ln248_6_fu_1695_p2;
wire   [9:0] tmp_13_fu_1701_p3;
wire   [5:0] sub_ln248_3_fu_1716_p2;
wire   [5:0] tmp_14_fu_1721_p4;
wire   [5:0] select_ln248_3_fu_1730_p3;
wire   [9:0] sext_ln248_3_cast_fu_1737_p3;
wire   [9:0] select_ln248_2_fu_1709_p3;
wire   [9:0] add_ln248_1_fu_1745_p2;
wire   [9:0] tmp_16_fu_1759_p3;
wire   [3:0] trunc_ln248_4_fu_1756_p1;
wire   [9:0] sub_ln248_9_fu_1766_p2;
wire   [9:0] tmp_17_fu_1772_p3;
wire   [5:0] sub_ln248_5_fu_1787_p2;
wire   [5:0] tmp_18_fu_1792_p4;
wire   [5:0] select_ln248_5_fu_1801_p3;
wire   [9:0] sext_ln248_5_cast_fu_1808_p3;
wire   [9:0] select_ln248_4_fu_1780_p3;
wire   [9:0] add_ln248_2_fu_1816_p2;
wire   [9:0] tmp_20_fu_1830_p3;
wire   [3:0] trunc_ln248_6_fu_1827_p1;
wire   [9:0] sub_ln248_11_fu_1837_p2;
wire   [9:0] tmp_21_fu_1843_p3;
wire   [5:0] sub_ln248_7_fu_1858_p2;
wire   [5:0] tmp_22_fu_1863_p4;
wire   [5:0] select_ln248_7_fu_1872_p3;
wire   [9:0] sext_ln248_7_cast_fu_1879_p3;
wire   [9:0] select_ln248_6_fu_1851_p3;
wire   [9:0] add_ln248_3_fu_1887_p2;
wire   [7:0] temp_0_0_fu_1898_p2;
wire   [5:0] add_ln173_fu_1920_p2;
wire   [1:0] lshr_ln1_fu_1950_p4;
wire   [4:0] tmp_25_fu_1968_p3;
wire   [8:0] tmp_24_fu_1960_p3;
wire   [8:0] zext_ln173_1_fu_1976_p1;
wire   [8:0] sub_ln173_fu_1980_p2;
wire   [8:0] add_ln173_1_fu_1986_p2;
wire   [0:0] tmp_26_fu_2002_p3;
wire   [31:0] select_ln173_1_fu_2010_p3;
wire   [31:0] select_ln173_fu_2018_p3;
wire   [31:0] select_ln173_2_fu_2045_p3;
wire   [2:0] shl_ln570_fu_2087_p2;
wire   [2:0] or_ln572_fu_2099_p2;
wire  signed [31:0] sext_ln140_1_fu_2117_p0;
wire  signed [31:0] sext_ln141_1_fu_2122_p0;
wire  signed [31:0] sext_ln146_1_fu_2127_p0;
wire  signed [31:0] sext_ln147_1_fu_2132_p0;
wire  signed [31:0] sext_ln142_1_fu_2137_p0;
wire  signed [31:0] sext_ln143_1_fu_2142_p0;
wire  signed [31:0] sext_ln149_1_fu_2147_p0;
wire  signed [31:0] sext_ln150_1_fu_2152_p0;
wire  signed [31:0] sext_ln153_1_fu_2157_p0;
wire  signed [31:0] sext_ln154_1_fu_2162_p0;
wire  signed [31:0] sext_ln159_1_fu_2167_p0;
wire  signed [31:0] sext_ln160_1_fu_2172_p0;
wire  signed [31:0] sext_ln155_1_fu_2197_p0;
wire  signed [31:0] sext_ln156_1_fu_2202_p0;
wire  signed [31:0] sext_ln161_1_fu_2207_p0;
wire  signed [31:0] sext_ln162_1_fu_2212_p0;
wire   [5:0] tmp_23_fu_2277_p3;
wire   [2:0] shl_ln384_fu_2305_p2;
wire   [2:0] or_ln393_fu_2317_p2;
wire   [31:0] j_0_i14_cast_fu_2289_p1;
wire   [31:0] add_ln393_fu_2329_p2;
wire   [8:0] trunc_ln393_fu_2340_p1;
wire   [8:0] add_ln417_fu_2344_p2;
wire   [23:0] tmp_27_fu_2362_p4;
wire   [31:0] and_ln_fu_2372_p3;
wire   [31:0] shl_ln384_1_fu_2356_p2;
wire   [0:0] icmp_ln385_fu_2380_p2;
wire   [31:0] xor_ln386_fu_2386_p2;
wire   [31:0] shl_ln388_fu_2400_p2;
wire   [31:0] x_1_fu_2406_p2;
wire   [23:0] tmp_28_fu_2412_p4;
wire   [31:0] and_ln1_fu_2422_p3;
wire   [0:0] icmp_ln389_fu_2430_p2;
wire   [31:0] xor_ln390_fu_2436_p2;
wire   [31:0] select_ln385_fu_2392_p3;
wire   [31:0] select_ln389_fu_2442_p3;
wire   [31:0] xor_ln393_1_fu_2456_p2;
wire   [31:0] xor_ln393_3_fu_2462_p2;
wire   [31:0] xor_ln393_fu_2450_p2;
wire   [23:0] tmp_29_fu_2474_p4;
wire   [31:0] and_ln2_fu_2484_p3;
wire   [0:0] icmp_ln397_fu_2492_p2;
wire   [31:0] xor_ln398_fu_2498_p2;
wire   [31:0] shl_ln400_fu_2512_p2;
wire   [31:0] x_3_fu_2518_p2;
wire   [23:0] tmp_30_fu_2524_p4;
wire   [31:0] and_ln3_fu_2534_p3;
wire   [0:0] icmp_ln401_fu_2542_p2;
wire   [31:0] xor_ln402_fu_2548_p2;
wire   [31:0] select_ln401_fu_2554_p3;
wire   [31:0] select_ln397_fu_2504_p3;
wire   [31:0] xor_ln405_1_fu_2568_p2;
wire   [31:0] xor_ln405_3_fu_2574_p2;
wire   [31:0] xor_ln405_fu_2562_p2;
wire   [23:0] tmp_31_fu_2586_p4;
wire   [31:0] and_ln4_fu_2596_p3;
wire   [0:0] icmp_ln409_fu_2604_p2;
wire   [31:0] xor_ln410_fu_2610_p2;
wire   [31:0] shl_ln412_fu_2624_p2;
wire   [31:0] x_5_fu_2630_p2;
wire   [23:0] tmp_32_fu_2636_p4;
wire   [31:0] and_ln5_fu_2646_p3;
wire   [0:0] icmp_ln413_fu_2654_p2;
wire   [31:0] xor_ln414_fu_2660_p2;
wire   [31:0] select_ln413_fu_2666_p3;
wire   [31:0] select_ln409_fu_2616_p3;
wire   [31:0] xor_ln417_1_fu_2680_p2;
wire   [31:0] xor_ln417_3_fu_2686_p2;
wire   [31:0] xor_ln417_fu_2674_p2;
wire   [23:0] tmp_33_fu_2698_p4;
wire   [31:0] and_ln6_fu_2708_p3;
wire   [0:0] icmp_ln421_fu_2716_p2;
wire   [31:0] xor_ln422_fu_2722_p2;
wire   [31:0] x_7_fu_2736_p2;
wire   [23:0] tmp_34_fu_2742_p4;
wire   [31:0] and_ln7_fu_2752_p3;
wire   [0:0] icmp_ln425_fu_2760_p2;
wire   [31:0] xor_ln426_fu_2766_p2;
wire   [31:0] select_ln425_fu_2772_p3;
wire   [31:0] select_ln421_fu_2728_p3;
wire   [31:0] xor_ln429_1_fu_2786_p2;
wire   [31:0] xor_ln429_3_fu_2792_p2;
wire   [31:0] xor_ln429_fu_2780_p2;
wire   [2:0] shl_ln437_fu_2816_p2;
wire   [2:0] or_ln439_fu_2828_p2;
wire  signed [31:0] sext_ln140_fu_2846_p0;
wire  signed [31:0] sext_ln141_fu_2851_p0;
wire  signed [31:0] sext_ln146_fu_2856_p0;
wire  signed [31:0] sext_ln147_fu_2861_p0;
wire  signed [31:0] sext_ln142_fu_2866_p0;
wire  signed [31:0] sext_ln143_fu_2871_p0;
wire  signed [31:0] sext_ln149_fu_2876_p0;
wire  signed [31:0] sext_ln150_fu_2881_p0;
wire  signed [31:0] sext_ln153_fu_2886_p0;
wire  signed [31:0] sext_ln154_fu_2891_p0;
wire  signed [31:0] sext_ln159_fu_2896_p0;
wire  signed [31:0] sext_ln160_fu_2901_p0;
wire  signed [31:0] sext_ln155_fu_2926_p0;
wire  signed [31:0] sext_ln156_fu_2931_p0;
wire  signed [31:0] sext_ln161_fu_2936_p0;
wire  signed [31:0] sext_ln162_fu_2941_p0;
wire   [5:0] or_ln_fu_3018_p3;
wire   [7:0] zext_ln570_4_fu_3032_p1;
wire   [7:0] add_ln572_fu_3036_p2;
wire   [2:0] shl_ln570_1_fu_3048_p2;
wire   [2:0] or_ln572_1_fu_3060_p2;
wire   [3:0] lshr_ln141_2_fu_3089_p4;
wire   [0:0] trunc_ln141_fu_3105_p1;
wire   [31:0] select_ln141_fu_3109_p3;
wire   [31:0] zext_ln141_3_fu_3117_p1;
wire   [0:0] icmp_ln141_fu_3121_p2;
wire   [31:0] zext_ln141_2_fu_3127_p1;
reg   [37:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 38'd1;
end

encrypt_Sbox #(
    .DataWidth( 8 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
Sbox_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(Sbox_address0),
    .ce0(Sbox_ce0),
    .q0(Sbox_q0),
    .address1(Sbox_address1),
    .ce1(Sbox_ce1),
    .q1(Sbox_q1),
    .address2(Sbox_address2),
    .ce2(Sbox_ce2),
    .q2(Sbox_q2),
    .address3(Sbox_address3),
    .ce3(Sbox_ce3),
    .q3(Sbox_q3)
);

encrypt_Rcon0 #(
    .DataWidth( 8 ),
    .AddressRange( 30 ),
    .AddressWidth( 5 ))
Rcon0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(Rcon0_address0),
    .ce0(Rcon0_ce0),
    .q0(Rcon0_q0)
);

encrypt_out_enc_sbkb #(
    .DataWidth( 8 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
out_enc_statemt_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(out_enc_statemt_address0),
    .ce0(out_enc_statemt_ce0),
    .q0(out_enc_statemt_q0)
);

encrypt_ret_0 #(
    .DataWidth( 32 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
ret_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(ret_0_address0),
    .ce0(ret_0_ce0),
    .we0(ret_0_we0),
    .d0(xor_ln393_2_reg_3681),
    .q0(ret_0_q0),
    .address1(ret_0_address1),
    .ce1(ret_0_ce1),
    .we1(ret_0_we1),
    .d1(xor_ln417_2_reg_3691),
    .q1(ret_0_q1)
);

encrypt_ret_0 #(
    .DataWidth( 32 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
ret_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(ret_1_address0),
    .ce0(ret_1_ce0),
    .we0(ret_1_we0),
    .d0(xor_ln405_2_reg_3686),
    .q0(ret_1_q0),
    .address1(ret_1_address1),
    .ce1(ret_1_ce1),
    .we1(ret_1_we1),
    .d1(xor_ln429_2_reg_3696),
    .q1(ret_1_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        i_0_i_reg_1096 <= i_reg_3168;
    end else if (((icmp_ln137_fu_1303_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_0_i_reg_1096 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        i_2_i_reg_1160 <= i_1_reg_3375;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        i_2_i_reg_1160 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln565_1_fu_3006_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state35))) begin
        i_2_reg_1227 <= 5'd0;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        i_2_reg_1227 <= i_3_reg_3877;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        j_0_i14_reg_1194 <= j_4_reg_3624;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        j_0_i14_reg_1194 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        j_0_i24_reg_1216 <= j_3_reg_3829;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        j_0_i24_reg_1216 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        j_0_i7_reg_1171 <= j_1_reg_3413;
    end else if (((icmp_ln146_fu_1431_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        j_0_i7_reg_1171 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln140_fu_1327_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        j_0_i_reg_1084 <= j_reg_3155;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        j_0_i_reg_1084 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln380_fu_2293_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state23))) begin
        j_1_i19_reg_1205 <= 3'd0;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        j_1_i19_reg_1205 <= j_5_reg_3704;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln137_fu_1303_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        j_1_i_reg_1108 <= 6'd4;
    end else if (((icmp_ln172_fu_1934_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
        j_1_i_reg_1108 <= j_2_fu_2034_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln433_fu_2804_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state26))) begin
        n_assign_reg_1182 <= i_4_fu_2840_p2;
    end else if (((icmp_ln565_fu_2059_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state13))) begin
        n_assign_reg_1182 <= 4'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state19))) begin
        reg_1271 <= Sbox_q0;
    end else if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state17))) begin
        reg_1271 <= Sbox_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state19))) begin
        reg_1276 <= Sbox_q1;
    end else if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state17))) begin
        reg_1276 <= Sbox_q2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state19))) begin
        reg_1281 <= Sbox_q2;
    end else if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state17))) begin
        reg_1281 <= Sbox_q3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state19))) begin
        reg_1286 <= Sbox_q3;
    end else if (((1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state18))) begin
        reg_1286 <= Sbox_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        temp_0_0_0_reg_1140 <= word_0_q0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        temp_0_0_0_reg_1140 <= zext_ln154_2_fu_1904_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        temp_0_1_0_reg_1130 <= word_0_q1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        temp_0_1_0_reg_1130 <= zext_ln248_1_fu_1912_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        temp_1335_0_0_reg_1120 <= word_1_q0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        temp_1335_0_0_reg_1120 <= zext_ln248_fu_1908_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        temp_1_1_reg_1150 <= word_1_q1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        temp_1_1_reg_1150 <= zext_ln248_3_fu_1916_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln172_fu_1934_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        add_ln173_2_reg_3390 <= add_ln173_2_fu_1997_p2;
        select_ln173_3_reg_3400 <= select_ln173_3_fu_2026_p3;
        trunc_ln173_reg_3380 <= trunc_ln173_fu_1946_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        i_1_reg_3375 <= i_1_fu_1940_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        i_3_reg_3877 <= i_3_fu_3078_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_reg_3168 <= i_fu_1333_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        j_1_reg_3413 <= j_1_fu_2065_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        j_3_reg_3829 <= j_3_fu_3012_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        j_4_reg_3624 <= j_4_fu_2299_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        j_5_reg_3704 <= j_5_fu_2810_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        j_reg_3155 <= j_fu_1309_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state17))) begin
        reg_1267 <= Sbox_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state20))) begin
        reg_1291 <= Sbox_q1;
        reg_1295 <= Sbox_q2;
        reg_1299 <= Sbox_q3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln137_fu_1303_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        shl_ln_reg_3160[3 : 2] <= shl_ln_fu_1319_p3[3 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln565_1_fu_3006_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state35))) begin
        statemt_0_addr_10_reg_3854[2 : 1] <= zext_ln570_2_fu_3054_p1[2 : 1];
        statemt_0_addr_11_reg_3864[2 : 1] <= zext_ln572_1_fu_3066_p1[2 : 1];
        statemt_1_addr_10_reg_3859[2 : 1] <= zext_ln570_2_fu_3054_p1[2 : 1];
        statemt_1_addr_11_reg_3869[2 : 1] <= zext_ln572_1_fu_3066_p1[2 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln565_fu_2059_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state13))) begin
        statemt_0_addr_1_reg_3448[2 : 1] <= zext_ln572_fu_2105_p1[2 : 1];
        statemt_0_addr_reg_3438[2 : 1] <= zext_ln570_1_fu_2093_p1[2 : 1];
        statemt_1_addr_1_reg_3453[2 : 1] <= zext_ln572_fu_2105_p1[2 : 1];
        statemt_1_addr_reg_3443[2 : 1] <= zext_ln570_1_fu_2093_p1[2 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        tmp_11_reg_3257 <= word_0_q0[32'd31];
        tmp_15_reg_3279 <= word_1_q1[32'd31];
        tmp_19_reg_3301 <= word_0_q1[32'd31];
        tmp_7_reg_3235 <= word_1_q0[32'd31];
        trunc_ln248_1_reg_3241 <= trunc_ln248_1_fu_1495_p1;
        trunc_ln248_3_reg_3263 <= trunc_ln248_3_fu_1523_p1;
        trunc_ln248_5_reg_3285 <= trunc_ln248_5_fu_1551_p1;
        trunc_ln248_7_reg_3307 <= trunc_ln248_7_fu_1579_p1;
        word_0_load_7_reg_3251 <= word_0_q0;
        word_0_load_8_reg_3295 <= word_0_q1;
        word_1_load_8_reg_3229 <= word_1_q0;
        word_1_load_9_reg_3273 <= word_1_q1;
        zext_ln248_2_reg_3268 <= {{sub_ln248_4_fu_1517_p2[9:4]}};
        zext_ln248_4_reg_3290 <= {{sub_ln248_8_fu_1545_p2[9:4]}};
        zext_ln248_6_reg_3312 <= {{sub_ln248_10_fu_1573_p2[9:4]}};
        zext_ln_reg_3246 <= {{sub_ln248_fu_1489_p2[9:4]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        xor_ln393_2_reg_3681 <= xor_ln393_2_fu_2468_p2;
        xor_ln405_2_reg_3686 <= xor_ln405_2_fu_2580_p2;
        xor_ln417_2_reg_3691 <= xor_ln417_2_fu_2692_p2;
        xor_ln429_2_reg_3696 <= xor_ln429_2_fu_2798_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        zext_ln172_reg_3367[5 : 0] <= zext_ln172_fu_1930_p1[5 : 0];
        zext_ln173_reg_3362[5 : 0] <= zext_ln173_fu_1926_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln380_fu_2293_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state23))) begin
        zext_ln384_reg_3629[2 : 1] <= zext_ln384_fu_2311_p1[2 : 1];
        zext_ln393_reg_3645[2 : 1] <= zext_ln393_fu_2323_p1[2 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        zext_ln393_2_reg_3616[5 : 2] <= zext_ln393_2_fu_2285_p1[5 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln433_fu_2804_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state26))) begin
        zext_ln437_reg_3709[2 : 1] <= zext_ln437_fu_2822_p1[2 : 1];
        zext_ln439_reg_3725[2 : 1] <= zext_ln439_fu_2834_p1[2 : 1];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        Rcon0_ce0 = 1'b1;
    end else begin
        Rcon0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        Sbox_address0 = sext_ln155_fu_2926_p1;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        Sbox_address0 = sext_ln153_fu_2886_p1;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        Sbox_address0 = sext_ln142_fu_2866_p1;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        Sbox_address0 = sext_ln140_fu_2846_p1;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        Sbox_address0 = sext_ln155_1_fu_2197_p1;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        Sbox_address0 = sext_ln153_1_fu_2157_p1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        Sbox_address0 = sext_ln142_1_fu_2137_p1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        Sbox_address0 = sext_ln140_1_fu_2117_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        Sbox_address0 = sext_ln248_fu_1659_p1;
    end else begin
        Sbox_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        Sbox_address1 = sext_ln156_fu_2931_p1;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        Sbox_address1 = sext_ln154_fu_2891_p1;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        Sbox_address1 = sext_ln143_fu_2871_p1;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        Sbox_address1 = sext_ln141_fu_2851_p1;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        Sbox_address1 = sext_ln156_1_fu_2202_p1;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        Sbox_address1 = sext_ln154_1_fu_2162_p1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        Sbox_address1 = sext_ln143_1_fu_2142_p1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        Sbox_address1 = sext_ln141_1_fu_2122_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        Sbox_address1 = sext_ln248_1_fu_1751_p1;
    end else begin
        Sbox_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        Sbox_address2 = sext_ln161_fu_2936_p1;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        Sbox_address2 = sext_ln159_fu_2896_p1;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        Sbox_address2 = sext_ln149_fu_2876_p1;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        Sbox_address2 = sext_ln146_fu_2856_p1;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        Sbox_address2 = sext_ln161_1_fu_2207_p1;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        Sbox_address2 = sext_ln159_1_fu_2167_p1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        Sbox_address2 = sext_ln149_1_fu_2147_p1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        Sbox_address2 = sext_ln146_1_fu_2127_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        Sbox_address2 = sext_ln248_2_fu_1822_p1;
    end else begin
        Sbox_address2 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        Sbox_address3 = sext_ln162_fu_2941_p1;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        Sbox_address3 = sext_ln160_fu_2901_p1;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        Sbox_address3 = sext_ln150_fu_2881_p1;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        Sbox_address3 = sext_ln147_fu_2861_p1;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        Sbox_address3 = sext_ln162_1_fu_2212_p1;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        Sbox_address3 = sext_ln160_1_fu_2172_p1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        Sbox_address3 = sext_ln150_1_fu_2152_p1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        Sbox_address3 = sext_ln147_1_fu_2132_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        Sbox_address3 = sext_ln248_3_fu_1893_p1;
    end else begin
        Sbox_address3 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state17))) begin
        Sbox_ce0 = 1'b1;
    end else begin
        Sbox_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state17))) begin
        Sbox_ce1 = 1'b1;
    end else begin
        Sbox_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state17))) begin
        Sbox_ce2 = 1'b1;
    end else begin
        Sbox_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state17))) begin
        Sbox_ce3 = 1'b1;
    end else begin
        Sbox_ce3 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln139_fu_3072_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state37)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln139_fu_3072_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state37))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        key_0_ce0 = 1'b1;
    end else begin
        key_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        main_result_o = add_ln141_fu_3135_p2;
    end else begin
        main_result_o = main_result_i;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        main_result_o_ap_vld = 1'b1;
    end else begin
        main_result_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        out_enc_statemt_ce0 = 1'b1;
    end else begin
        out_enc_statemt_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        ret_0_address0 = zext_ln437_fu_2822_p1;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        ret_0_address0 = zext_ln384_reg_3629;
    end else begin
        ret_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        ret_0_address1 = zext_ln439_fu_2834_p1;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        ret_0_address1 = zext_ln393_reg_3645;
    end else begin
        ret_0_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state26))) begin
        ret_0_ce0 = 1'b1;
    end else begin
        ret_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state26))) begin
        ret_0_ce1 = 1'b1;
    end else begin
        ret_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        ret_0_we0 = 1'b1;
    end else begin
        ret_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        ret_0_we1 = 1'b1;
    end else begin
        ret_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        ret_1_address0 = zext_ln437_fu_2822_p1;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        ret_1_address0 = zext_ln384_reg_3629;
    end else begin
        ret_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        ret_1_address1 = zext_ln439_fu_2834_p1;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        ret_1_address1 = zext_ln393_reg_3645;
    end else begin
        ret_1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state26))) begin
        ret_1_ce0 = 1'b1;
    end else begin
        ret_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state26))) begin
        ret_1_ce1 = 1'b1;
    end else begin
        ret_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        ret_1_we0 = 1'b1;
    end else begin
        ret_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        ret_1_we1 = 1'b1;
    end else begin
        ret_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln146_fu_1431_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        round_val_ap_vld = 1'b1;
    end else begin
        round_val_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        statemt_0_address0 = zext_ln141_1_fu_3099_p1;
    end else if ((1'b1 == ap_CS_fsm_state36)) begin
        statemt_0_address0 = statemt_0_addr_10_reg_3854;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        statemt_0_address0 = zext_ln570_2_fu_3054_p1;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        statemt_0_address0 = zext_ln437_reg_3709;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        statemt_0_address0 = zext_ln384_fu_2311_p1;
    end else if (((1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state18))) begin
        statemt_0_address0 = 64'd4;
    end else if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state17))) begin
        statemt_0_address0 = 64'd0;
    end else if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state20))) begin
        statemt_0_address0 = 64'd3;
    end else if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state19) | ((icmp_ln112_fu_2111_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15)) | ((icmp_ln112_fu_2111_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state15)))) begin
        statemt_0_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        statemt_0_address0 = statemt_0_addr_reg_3438;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        statemt_0_address0 = zext_ln570_1_fu_2093_p1;
    end else begin
        statemt_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        statemt_0_address1 = statemt_0_addr_11_reg_3864;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        statemt_0_address1 = zext_ln572_1_fu_3066_p1;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        statemt_0_address1 = zext_ln439_reg_3725;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        statemt_0_address1 = zext_ln393_fu_2323_p1;
    end else if (((1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state18))) begin
        statemt_0_address1 = 64'd6;
    end else if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state17))) begin
        statemt_0_address1 = 64'd2;
    end else if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state20))) begin
        statemt_0_address1 = 64'd7;
    end else if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state19) | ((icmp_ln112_fu_2111_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15)) | ((icmp_ln112_fu_2111_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state15)))) begin
        statemt_0_address1 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        statemt_0_address1 = statemt_0_addr_1_reg_3448;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        statemt_0_address1 = zext_ln572_fu_2105_p1;
    end else begin
        statemt_0_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state17) | ((icmp_ln112_fu_2111_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15)) | ((icmp_ln112_fu_2111_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state15)))) begin
        statemt_0_ce0 = 1'b1;
    end else begin
        statemt_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state17) | ((icmp_ln112_fu_2111_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15)) | ((icmp_ln112_fu_2111_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state15)))) begin
        statemt_0_ce1 = 1'b1;
    end else begin
        statemt_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        statemt_0_d0 = zext_ln161_fu_2996_p1;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        statemt_0_d0 = zext_ln159_fu_2976_p1;
    end else if ((1'b1 == ap_CS_fsm_state32)) begin
        statemt_0_d0 = zext_ln150_fu_2961_p1;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        statemt_0_d0 = zext_ln147_fu_2921_p1;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        statemt_0_d0 = ret_0_q0;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        statemt_0_d0 = zext_ln161_1_fu_2267_p1;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        statemt_0_d0 = zext_ln159_1_fu_2247_p1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        statemt_0_d0 = zext_ln150_1_fu_2232_p1;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        statemt_0_d0 = zext_ln147_1_fu_2192_p1;
    end else if (((1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state14))) begin
        statemt_0_d0 = grp_fu_1239_p2;
    end else begin
        statemt_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        statemt_0_d1 = zext_ln162_fu_3001_p1;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        statemt_0_d1 = zext_ln160_fu_2981_p1;
    end else if ((1'b1 == ap_CS_fsm_state32)) begin
        statemt_0_d1 = zext_ln149_fu_2956_p1;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        statemt_0_d1 = zext_ln146_fu_2916_p1;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        statemt_0_d1 = ret_0_q1;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        statemt_0_d1 = zext_ln162_1_fu_2272_p1;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        statemt_0_d1 = zext_ln160_1_fu_2252_p1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        statemt_0_d1 = zext_ln149_1_fu_2227_p1;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        statemt_0_d1 = zext_ln146_1_fu_2187_p1;
    end else if (((1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state14))) begin
        statemt_0_d1 = grp_fu_1253_p2;
    end else begin
        statemt_0_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state20))) begin
        statemt_0_we0 = 1'b1;
    end else begin
        statemt_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state20))) begin
        statemt_0_we1 = 1'b1;
    end else begin
        statemt_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        statemt_1_address0 = zext_ln141_1_fu_3099_p1;
    end else if ((1'b1 == ap_CS_fsm_state36)) begin
        statemt_1_address0 = statemt_1_addr_10_reg_3859;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        statemt_1_address0 = zext_ln570_2_fu_3054_p1;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        statemt_1_address0 = zext_ln437_reg_3709;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        statemt_1_address0 = zext_ln384_fu_2311_p1;
    end else if (((1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state18))) begin
        statemt_1_address0 = 64'd5;
    end else if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state17))) begin
        statemt_1_address0 = 64'd1;
    end else if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state20))) begin
        statemt_1_address0 = 64'd4;
    end else if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state19) | ((icmp_ln112_fu_2111_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15)) | ((icmp_ln112_fu_2111_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state15)))) begin
        statemt_1_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        statemt_1_address0 = statemt_1_addr_reg_3443;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        statemt_1_address0 = zext_ln570_1_fu_2093_p1;
    end else begin
        statemt_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        statemt_1_address1 = statemt_1_addr_11_reg_3869;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        statemt_1_address1 = zext_ln572_1_fu_3066_p1;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        statemt_1_address1 = zext_ln439_reg_3725;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        statemt_1_address1 = zext_ln393_fu_2323_p1;
    end else if (((1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state18))) begin
        statemt_1_address1 = 64'd3;
    end else if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state17))) begin
        statemt_1_address1 = 64'd7;
    end else if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state20))) begin
        statemt_1_address1 = 64'd6;
    end else if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state19) | ((icmp_ln112_fu_2111_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15)) | ((icmp_ln112_fu_2111_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state15)))) begin
        statemt_1_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        statemt_1_address1 = statemt_1_addr_1_reg_3453;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        statemt_1_address1 = zext_ln572_fu_2105_p1;
    end else begin
        statemt_1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state17) | ((icmp_ln112_fu_2111_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15)) | ((icmp_ln112_fu_2111_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state15)))) begin
        statemt_1_ce0 = 1'b1;
    end else begin
        statemt_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state17) | ((icmp_ln112_fu_2111_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15)) | ((icmp_ln112_fu_2111_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state15)))) begin
        statemt_1_ce1 = 1'b1;
    end else begin
        statemt_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        statemt_1_d0 = zext_ln156_fu_2991_p1;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        statemt_1_d0 = zext_ln154_3_fu_2966_p1;
    end else if ((1'b1 == ap_CS_fsm_state32)) begin
        statemt_1_d0 = zext_ln143_fu_2951_p1;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        statemt_1_d0 = zext_ln141_4_fu_2906_p1;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        statemt_1_d0 = ret_1_q0;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        statemt_1_d0 = zext_ln156_1_fu_2262_p1;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        statemt_1_d0 = zext_ln154_4_fu_2237_p1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        statemt_1_d0 = zext_ln143_1_fu_2222_p1;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        statemt_1_d0 = zext_ln141_5_fu_2177_p1;
    end else if (((1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state14))) begin
        statemt_1_d0 = grp_fu_1246_p2;
    end else begin
        statemt_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        statemt_1_d1 = zext_ln153_fu_2986_p1;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        statemt_1_d1 = zext_ln155_2_fu_2971_p1;
    end else if ((1'b1 == ap_CS_fsm_state32)) begin
        statemt_1_d1 = zext_ln140_fu_2946_p1;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        statemt_1_d1 = zext_ln142_4_fu_2911_p1;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        statemt_1_d1 = ret_1_q1;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        statemt_1_d1 = zext_ln153_1_fu_2257_p1;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        statemt_1_d1 = zext_ln155_3_fu_2242_p1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        statemt_1_d1 = zext_ln140_1_fu_2217_p1;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        statemt_1_d1 = zext_ln142_5_fu_2182_p1;
    end else if (((1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state14))) begin
        statemt_1_d1 = grp_fu_1260_p2;
    end else begin
        statemt_1_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state20))) begin
        statemt_1_we0 = 1'b1;
    end else begin
        statemt_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state20))) begin
        statemt_1_we1 = 1'b1;
    end else begin
        statemt_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        word_0_address0 = zext_ln572_2_fu_3042_p1;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        word_0_address0 = zext_ln417_fu_2350_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        word_0_address0 = tmp_s_fu_2077_p3;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        word_0_address0 = sext_ln173_1_fu_2040_p1;
    end else if (((icmp_ln152_fu_1441_p2 == 1'd1) & (icmp_ln146_fu_1431_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        word_0_address0 = zext_ln155_1_fu_1469_p1;
    end else if (((icmp_ln152_fu_1441_p2 == 1'd0) & (icmp_ln146_fu_1431_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        word_0_address0 = zext_ln154_fu_1453_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        word_0_address0 = sext_ln142_2_fu_1425_p1;
    end else begin
        word_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        word_0_address1 = zext_ln570_3_fu_3026_p1;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        word_0_address1 = zext_ln393_1_fu_2334_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        word_0_address1 = zext_ln570_fu_2071_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        word_0_address1 = sext_ln173_fu_1991_p1;
    end else if (((icmp_ln152_fu_1441_p2 == 1'd1) & (icmp_ln146_fu_1431_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        word_0_address1 = zext_ln154_fu_1453_p1;
    end else if (((icmp_ln152_fu_1441_p2 == 1'd0) & (icmp_ln146_fu_1431_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        word_0_address1 = zext_ln155_1_fu_1469_p1;
    end else begin
        word_0_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state13) | ((icmp_ln152_fu_1441_p2 == 1'd1) & (icmp_ln146_fu_1431_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln152_fu_1441_p2 == 1'd0) & (icmp_ln146_fu_1431_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)))) begin
        word_0_ce0 = 1'b1;
    end else begin
        word_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state11) | ((icmp_ln152_fu_1441_p2 == 1'd1) & (icmp_ln146_fu_1431_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln152_fu_1441_p2 == 1'd0) & (icmp_ln146_fu_1431_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)))) begin
        word_0_ce1 = 1'b1;
    end else begin
        word_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        word_0_d0 = xor_ln173_fu_2052_p2;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        word_0_d0 = key_0_q0;
    end else begin
        word_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln173_reg_3380 == 1'd0) & (1'b1 == ap_CS_fsm_state12)) | ((trunc_ln142_1_fu_1353_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state4)))) begin
        word_0_we0 = 1'b1;
    end else begin
        word_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        word_1_address0 = zext_ln572_2_fu_3042_p1;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        word_1_address0 = zext_ln417_fu_2350_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        word_1_address0 = tmp_s_fu_2077_p3;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        word_1_address0 = sext_ln173_1_fu_2040_p1;
    end else if ((((icmp_ln152_fu_1441_p2 == 1'd1) & (icmp_ln146_fu_1431_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln152_fu_1441_p2 == 1'd0) & (icmp_ln146_fu_1431_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)))) begin
        word_1_address0 = zext_ln154_fu_1453_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        word_1_address0 = sext_ln142_2_fu_1425_p1;
    end else begin
        word_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        word_1_address1 = zext_ln570_3_fu_3026_p1;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        word_1_address1 = zext_ln393_1_fu_2334_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        word_1_address1 = zext_ln570_fu_2071_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        word_1_address1 = sext_ln173_fu_1991_p1;
    end else if ((((icmp_ln152_fu_1441_p2 == 1'd1) & (icmp_ln146_fu_1431_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln152_fu_1441_p2 == 1'd0) & (icmp_ln146_fu_1431_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)))) begin
        word_1_address1 = zext_ln155_1_fu_1469_p1;
    end else begin
        word_1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state13) | ((icmp_ln152_fu_1441_p2 == 1'd1) & (icmp_ln146_fu_1431_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln152_fu_1441_p2 == 1'd0) & (icmp_ln146_fu_1431_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)))) begin
        word_1_ce0 = 1'b1;
    end else begin
        word_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state11) | ((icmp_ln152_fu_1441_p2 == 1'd1) & (icmp_ln146_fu_1431_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln152_fu_1441_p2 == 1'd0) & (icmp_ln146_fu_1431_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)))) begin
        word_1_ce1 = 1'b1;
    end else begin
        word_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        word_1_d0 = xor_ln173_fu_2052_p2;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        word_1_d0 = key_0_q0;
    end else begin
        word_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln173_reg_3380 == 1'd1) & (1'b1 == ap_CS_fsm_state12)) | ((trunc_ln142_1_fu_1353_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state4)))) begin
        word_1_we0 = 1'b1;
    end else begin
        word_1_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln137_fu_1303_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln140_fu_1327_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state5 : begin
            if (((icmp_ln146_fu_1431_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else if (((icmp_ln152_fu_1441_p2 == 1'd1) & (icmp_ln146_fu_1431_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((icmp_ln172_fu_1934_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state13 : begin
            if (((icmp_ln565_fu_2059_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state15 : begin
            if (((icmp_ln112_fu_2111_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            if (((icmp_ln380_fu_2293_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state23))) begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state26 : begin
            if (((icmp_ln433_fu_2804_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state26))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            if (((icmp_ln565_1_fu_3006_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state35))) begin
                ap_NS_fsm = ap_ST_fsm_state37;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state36;
            end
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state37 : begin
            if (((icmp_ln139_fu_3072_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state37))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state38;
            end
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Rcon0_address0 = zext_ln154_1_fu_1680_p1;

assign add_ln141_fu_3135_p2 = (main_result_i + zext_ln141_2_fu_3127_p1);

assign add_ln142_fu_1343_p2 = (shl_ln_reg_3160 + zext_ln142_fu_1339_p1);

assign add_ln154_1_fu_1674_p2 = ($signed(4'd15) + $signed(trunc_ln154_1_fu_1664_p4));

assign add_ln154_fu_1447_p2 = ($signed(6'd63) + $signed(j_1_i_reg_1108));

assign add_ln155_fu_1463_p2 = (8'd120 + zext_ln155_fu_1459_p1);

assign add_ln173_1_fu_1986_p2 = (zext_ln173_reg_3362 + sub_ln173_fu_1980_p2);

assign add_ln173_2_fu_1997_p2 = (zext_ln172_reg_3367 + sub_ln173_fu_1980_p2);

assign add_ln173_fu_1920_p2 = ($signed(j_1_i_reg_1108) + $signed(6'd60));

assign add_ln248_1_fu_1745_p2 = (sext_ln248_3_cast_fu_1737_p3 + select_ln248_2_fu_1709_p3);

assign add_ln248_2_fu_1816_p2 = (sext_ln248_5_cast_fu_1808_p3 + select_ln248_4_fu_1780_p3);

assign add_ln248_3_fu_1887_p2 = (sext_ln248_7_cast_fu_1879_p3 + select_ln248_6_fu_1851_p3);

assign add_ln248_fu_1653_p2 = (sext_ln248_1_cast_fu_1645_p3 + select_ln248_fu_1617_p3);

assign add_ln393_fu_2329_p2 = (j_0_i14_cast_fu_2289_p1 + zext_ln393_2_reg_3616);

assign add_ln417_fu_2344_p2 = (9'd120 + trunc_ln393_fu_2340_p1);

assign add_ln572_fu_3036_p2 = (8'd120 + zext_ln570_4_fu_3032_p1);

assign and_ln1_fu_2422_p3 = {{tmp_28_fu_2412_p4}, {8'd0}};

assign and_ln2_fu_2484_p3 = {{tmp_29_fu_2474_p4}, {8'd0}};

assign and_ln3_fu_2534_p3 = {{tmp_30_fu_2524_p4}, {8'd0}};

assign and_ln4_fu_2596_p3 = {{tmp_31_fu_2586_p4}, {8'd0}};

assign and_ln5_fu_2646_p3 = {{tmp_32_fu_2636_p4}, {8'd0}};

assign and_ln6_fu_2708_p3 = {{tmp_33_fu_2698_p4}, {8'd0}};

assign and_ln7_fu_2752_p3 = {{tmp_34_fu_2742_p4}, {8'd0}};

assign and_ln_fu_2372_p3 = {{tmp_27_fu_2362_p4}, {8'd0}};

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign grp_fu_1239_p2 = (word_0_q1 ^ statemt_0_q0);

assign grp_fu_1246_p2 = (word_1_q1 ^ statemt_1_q0);

assign grp_fu_1253_p2 = (word_0_q0 ^ statemt_0_q1);

assign grp_fu_1260_p2 = (word_1_q0 ^ statemt_1_q1);

assign i_1_fu_1940_p2 = (i_2_i_reg_1160 + 3'd1);

assign i_3_fu_3078_p2 = (i_2_reg_1227 + 5'd1);

assign i_4_fu_2840_p2 = (n_assign_reg_1182 + 4'd1);

assign i_fu_1333_p2 = (i_0_i_reg_1096 + 3'd1);

assign icmp_ln112_fu_2111_p2 = ((n_assign_reg_1182 == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln137_fu_1303_p2 = ((j_0_i_reg_1084 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln139_fu_3072_p2 = ((i_2_reg_1227 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln140_fu_1327_p2 = ((i_0_i_reg_1096 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln141_fu_3121_p2 = ((select_ln141_fu_3109_p3 != zext_ln141_3_fu_3117_p1) ? 1'b1 : 1'b0);

assign icmp_ln146_fu_1431_p2 = ((j_1_i_reg_1108 == 6'd44) ? 1'b1 : 1'b0);

assign icmp_ln152_fu_1441_p2 = ((trunc_ln146_fu_1437_p1 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln172_fu_1934_p2 = ((i_2_i_reg_1160 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln380_fu_2293_p2 = ((j_0_i14_reg_1194 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln385_fu_2380_p2 = ((and_ln_fu_2372_p3 == 32'd256) ? 1'b1 : 1'b0);

assign icmp_ln389_fu_2430_p2 = ((and_ln1_fu_2422_p3 == 32'd256) ? 1'b1 : 1'b0);

assign icmp_ln397_fu_2492_p2 = ((and_ln2_fu_2484_p3 == 32'd256) ? 1'b1 : 1'b0);

assign icmp_ln401_fu_2542_p2 = ((and_ln3_fu_2534_p3 == 32'd256) ? 1'b1 : 1'b0);

assign icmp_ln409_fu_2604_p2 = ((and_ln4_fu_2596_p3 == 32'd256) ? 1'b1 : 1'b0);

assign icmp_ln413_fu_2654_p2 = ((and_ln5_fu_2646_p3 == 32'd256) ? 1'b1 : 1'b0);

assign icmp_ln421_fu_2716_p2 = ((and_ln6_fu_2708_p3 == 32'd256) ? 1'b1 : 1'b0);

assign icmp_ln425_fu_2760_p2 = ((and_ln7_fu_2752_p3 == 32'd256) ? 1'b1 : 1'b0);

assign icmp_ln433_fu_2804_p2 = ((j_1_i19_reg_1205 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln565_1_fu_3006_p2 = ((j_0_i24_reg_1216 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln565_fu_2059_p2 = ((j_0_i7_reg_1171 == 3'd4) ? 1'b1 : 1'b0);

assign j_0_i14_cast_fu_2289_p1 = j_0_i14_reg_1194;

assign j_1_fu_2065_p2 = (j_0_i7_reg_1171 + 3'd1);

assign j_2_fu_2034_p2 = (j_1_i_reg_1108 + 6'd1);

assign j_3_fu_3012_p2 = (j_0_i24_reg_1216 + 3'd1);

assign j_4_fu_2299_p2 = (j_0_i14_reg_1194 + 3'd1);

assign j_5_fu_2810_p2 = (j_1_i19_reg_1205 + 3'd1);

assign j_fu_1309_p2 = (j_0_i_reg_1084 + 3'd1);

assign key_0_address0 = zext_ln142_1_fu_1348_p1;

assign lshr_ln141_2_fu_3089_p4 = {{i_2_reg_1227[4:1]}};

assign lshr_ln1_fu_1950_p4 = {{i_2_i_reg_1160[2:1]}};

assign lshr_ln_fu_1357_p4 = {{i_0_i_reg_1096[2:1]}};

assign or_ln142_fu_1401_p2 = (trunc_ln142_2_fu_1397_p1 | j_0_i_reg_1084);

assign or_ln393_fu_2317_p2 = (shl_ln384_fu_2305_p2 | 3'd1);

assign or_ln439_fu_2828_p2 = (shl_ln437_fu_2816_p2 | 3'd1);

assign or_ln572_1_fu_3060_p2 = (shl_ln570_1_fu_3048_p2 | 3'd1);

assign or_ln572_fu_2099_p2 = (shl_ln570_fu_2087_p2 | 3'd1);

assign or_ln_fu_3018_p3 = {{3'd5}, {j_0_i24_reg_1216}};

assign out_enc_statemt_address0 = zext_ln141_fu_3084_p1;

assign round_val = 5'd0;

assign select_ln141_fu_3109_p3 = ((trunc_ln141_fu_3105_p1[0:0] === 1'b1) ? statemt_1_q0 : statemt_0_q0);

assign select_ln173_1_fu_2010_p3 = ((tmp_26_fu_2002_p3[0:0] === 1'b1) ? temp_1_1_reg_1150 : temp_1335_0_0_reg_1120);

assign select_ln173_2_fu_2045_p3 = ((trunc_ln173_reg_3380[0:0] === 1'b1) ? word_1_q1 : word_0_q1);

assign select_ln173_3_fu_2026_p3 = ((trunc_ln173_fu_1946_p1[0:0] === 1'b1) ? select_ln173_1_fu_2010_p3 : select_ln173_fu_2018_p3);

assign select_ln173_fu_2018_p3 = ((tmp_26_fu_2002_p3[0:0] === 1'b1) ? temp_0_1_0_reg_1130 : temp_0_0_0_reg_1140);

assign select_ln248_1_fu_1638_p3 = ((tmp_7_reg_3235[0:0] === 1'b1) ? sub_ln248_1_fu_1624_p2 : tmp_10_fu_1629_p4);

assign select_ln248_2_fu_1709_p3 = ((tmp_11_reg_3257[0:0] === 1'b1) ? sub_ln248_6_fu_1695_p2 : tmp_13_fu_1701_p3);

assign select_ln248_3_fu_1730_p3 = ((tmp_11_reg_3257[0:0] === 1'b1) ? sub_ln248_3_fu_1716_p2 : tmp_14_fu_1721_p4);

assign select_ln248_4_fu_1780_p3 = ((tmp_15_reg_3279[0:0] === 1'b1) ? sub_ln248_9_fu_1766_p2 : tmp_17_fu_1772_p3);

assign select_ln248_5_fu_1801_p3 = ((tmp_15_reg_3279[0:0] === 1'b1) ? sub_ln248_5_fu_1787_p2 : tmp_18_fu_1792_p4);

assign select_ln248_6_fu_1851_p3 = ((tmp_19_reg_3301[0:0] === 1'b1) ? sub_ln248_11_fu_1837_p2 : tmp_21_fu_1843_p3);

assign select_ln248_7_fu_1872_p3 = ((tmp_19_reg_3301[0:0] === 1'b1) ? sub_ln248_7_fu_1858_p2 : tmp_22_fu_1863_p4);

assign select_ln248_fu_1617_p3 = ((tmp_7_reg_3235[0:0] === 1'b1) ? sub_ln248_2_fu_1603_p2 : tmp_9_fu_1609_p3);

assign select_ln385_fu_2392_p3 = ((icmp_ln385_fu_2380_p2[0:0] === 1'b1) ? xor_ln386_fu_2386_p2 : shl_ln384_1_fu_2356_p2);

assign select_ln389_fu_2442_p3 = ((icmp_ln389_fu_2430_p2[0:0] === 1'b1) ? xor_ln390_fu_2436_p2 : x_1_fu_2406_p2);

assign select_ln397_fu_2504_p3 = ((icmp_ln397_fu_2492_p2[0:0] === 1'b1) ? xor_ln398_fu_2498_p2 : shl_ln388_fu_2400_p2);

assign select_ln401_fu_2554_p3 = ((icmp_ln401_fu_2542_p2[0:0] === 1'b1) ? xor_ln402_fu_2548_p2 : x_3_fu_2518_p2);

assign select_ln409_fu_2616_p3 = ((icmp_ln409_fu_2604_p2[0:0] === 1'b1) ? xor_ln410_fu_2610_p2 : shl_ln400_fu_2512_p2);

assign select_ln413_fu_2666_p3 = ((icmp_ln413_fu_2654_p2[0:0] === 1'b1) ? xor_ln414_fu_2660_p2 : x_5_fu_2630_p2);

assign select_ln421_fu_2728_p3 = ((icmp_ln421_fu_2716_p2[0:0] === 1'b1) ? xor_ln422_fu_2722_p2 : shl_ln412_fu_2624_p2);

assign select_ln425_fu_2772_p3 = ((icmp_ln425_fu_2760_p2[0:0] === 1'b1) ? xor_ln426_fu_2766_p2 : x_7_fu_2736_p2);

assign sext_ln140_1_fu_2117_p0 = statemt_1_q0;

assign sext_ln140_1_fu_2117_p1 = sext_ln140_1_fu_2117_p0;

assign sext_ln140_fu_2846_p0 = statemt_1_q0;

assign sext_ln140_fu_2846_p1 = sext_ln140_fu_2846_p0;

assign sext_ln141_1_fu_2122_p0 = statemt_1_q1;

assign sext_ln141_1_fu_2122_p1 = sext_ln141_1_fu_2122_p0;

assign sext_ln141_fu_2851_p0 = statemt_1_q1;

assign sext_ln141_fu_2851_p1 = sext_ln141_fu_2851_p0;

assign sext_ln142_1_fu_2137_p0 = statemt_1_q0;

assign sext_ln142_1_fu_2137_p1 = sext_ln142_1_fu_2137_p0;

assign sext_ln142_2_fu_1425_p1 = $signed(tmp_6_fu_1417_p3);

assign sext_ln142_fu_2866_p0 = statemt_1_q0;

assign sext_ln142_fu_2866_p1 = sext_ln142_fu_2866_p0;

assign sext_ln143_1_fu_2142_p0 = statemt_1_q1;

assign sext_ln143_1_fu_2142_p1 = sext_ln143_1_fu_2142_p0;

assign sext_ln143_fu_2871_p0 = statemt_1_q1;

assign sext_ln143_fu_2871_p1 = sext_ln143_fu_2871_p0;

assign sext_ln146_1_fu_2127_p0 = statemt_0_q0;

assign sext_ln146_1_fu_2127_p1 = sext_ln146_1_fu_2127_p0;

assign sext_ln146_fu_2856_p0 = statemt_0_q0;

assign sext_ln146_fu_2856_p1 = sext_ln146_fu_2856_p0;

assign sext_ln147_1_fu_2132_p0 = statemt_0_q1;

assign sext_ln147_1_fu_2132_p1 = sext_ln147_1_fu_2132_p0;

assign sext_ln147_fu_2861_p0 = statemt_0_q1;

assign sext_ln147_fu_2861_p1 = sext_ln147_fu_2861_p0;

assign sext_ln149_1_fu_2147_p0 = statemt_0_q0;

assign sext_ln149_1_fu_2147_p1 = sext_ln149_1_fu_2147_p0;

assign sext_ln149_fu_2876_p0 = statemt_0_q0;

assign sext_ln149_fu_2876_p1 = sext_ln149_fu_2876_p0;

assign sext_ln150_1_fu_2152_p0 = statemt_0_q1;

assign sext_ln150_1_fu_2152_p1 = sext_ln150_1_fu_2152_p0;

assign sext_ln150_fu_2881_p0 = statemt_0_q1;

assign sext_ln150_fu_2881_p1 = sext_ln150_fu_2881_p0;

assign sext_ln153_1_fu_2157_p0 = statemt_1_q0;

assign sext_ln153_1_fu_2157_p1 = sext_ln153_1_fu_2157_p0;

assign sext_ln153_fu_2886_p0 = statemt_1_q0;

assign sext_ln153_fu_2886_p1 = sext_ln153_fu_2886_p0;

assign sext_ln154_1_fu_2162_p0 = statemt_1_q1;

assign sext_ln154_1_fu_2162_p1 = sext_ln154_1_fu_2162_p0;

assign sext_ln154_fu_2891_p0 = statemt_1_q1;

assign sext_ln154_fu_2891_p1 = sext_ln154_fu_2891_p0;

assign sext_ln155_1_fu_2197_p0 = statemt_1_q0;

assign sext_ln155_1_fu_2197_p1 = sext_ln155_1_fu_2197_p0;

assign sext_ln155_fu_2926_p0 = statemt_1_q0;

assign sext_ln155_fu_2926_p1 = sext_ln155_fu_2926_p0;

assign sext_ln156_1_fu_2202_p0 = statemt_1_q1;

assign sext_ln156_1_fu_2202_p1 = sext_ln156_1_fu_2202_p0;

assign sext_ln156_fu_2931_p0 = statemt_1_q1;

assign sext_ln156_fu_2931_p1 = sext_ln156_fu_2931_p0;

assign sext_ln159_1_fu_2167_p0 = statemt_0_q0;

assign sext_ln159_1_fu_2167_p1 = sext_ln159_1_fu_2167_p0;

assign sext_ln159_fu_2896_p0 = statemt_0_q0;

assign sext_ln159_fu_2896_p1 = sext_ln159_fu_2896_p0;

assign sext_ln160_1_fu_2172_p0 = statemt_0_q1;

assign sext_ln160_1_fu_2172_p1 = sext_ln160_1_fu_2172_p0;

assign sext_ln160_fu_2901_p0 = statemt_0_q1;

assign sext_ln160_fu_2901_p1 = sext_ln160_fu_2901_p0;

assign sext_ln161_1_fu_2207_p0 = statemt_0_q0;

assign sext_ln161_1_fu_2207_p1 = sext_ln161_1_fu_2207_p0;

assign sext_ln161_fu_2936_p0 = statemt_0_q0;

assign sext_ln161_fu_2936_p1 = sext_ln161_fu_2936_p0;

assign sext_ln162_1_fu_2212_p0 = statemt_0_q1;

assign sext_ln162_1_fu_2212_p1 = sext_ln162_1_fu_2212_p0;

assign sext_ln162_fu_2941_p0 = statemt_0_q1;

assign sext_ln162_fu_2941_p1 = sext_ln162_fu_2941_p0;

assign sext_ln173_1_fu_2040_p1 = $signed(add_ln173_2_reg_3390);

assign sext_ln173_fu_1991_p1 = $signed(add_ln173_1_fu_1986_p2);

assign sext_ln248_1_cast_fu_1645_p3 = {{select_ln248_1_fu_1638_p3}, {4'd0}};

assign sext_ln248_1_fu_1751_p1 = $signed(add_ln248_1_fu_1745_p2);

assign sext_ln248_2_fu_1822_p1 = $signed(add_ln248_2_fu_1816_p2);

assign sext_ln248_3_cast_fu_1737_p3 = {{select_ln248_3_fu_1730_p3}, {4'd0}};

assign sext_ln248_3_fu_1893_p1 = $signed(add_ln248_3_fu_1887_p2);

assign sext_ln248_5_cast_fu_1808_p3 = {{select_ln248_5_fu_1801_p3}, {4'd0}};

assign sext_ln248_7_cast_fu_1879_p3 = {{select_ln248_7_fu_1872_p3}, {4'd0}};

assign sext_ln248_fu_1659_p1 = $signed(add_ln248_fu_1653_p2);

assign shl_ln384_1_fu_2356_p2 = statemt_0_q0 << 32'd1;

assign shl_ln384_fu_2305_p2 = j_0_i14_reg_1194 << 3'd1;

assign shl_ln388_fu_2400_p2 = statemt_1_q0 << 32'd1;

assign shl_ln400_fu_2512_p2 = statemt_0_q1 << 32'd1;

assign shl_ln412_fu_2624_p2 = statemt_1_q1 << 32'd1;

assign shl_ln437_fu_2816_p2 = j_1_i19_reg_1205 << 3'd1;

assign shl_ln570_1_fu_3048_p2 = j_0_i24_reg_1216 << 3'd1;

assign shl_ln570_fu_2087_p2 = j_0_i7_reg_1171 << 3'd1;

assign shl_ln_fu_1319_p3 = {{trunc_ln142_fu_1315_p1}, {2'd0}};

assign sub_ln142_fu_1391_p2 = (zext_ln142_2_fu_1375_p1 - zext_ln142_3_fu_1387_p1);

assign sub_ln173_fu_1980_p2 = (tmp_24_fu_1960_p3 - zext_ln173_1_fu_1976_p1);

assign sub_ln248_10_fu_1573_p2 = (32'd0 - word_0_q1);

assign sub_ln248_11_fu_1837_p2 = (10'd0 - tmp_20_fu_1830_p3);

assign sub_ln248_1_fu_1624_p2 = (6'd0 - zext_ln_reg_3246);

assign sub_ln248_2_fu_1603_p2 = (10'd0 - tmp_8_fu_1596_p3);

assign sub_ln248_3_fu_1716_p2 = (6'd0 - zext_ln248_2_reg_3268);

assign sub_ln248_4_fu_1517_p2 = (32'd0 - word_0_q0);

assign sub_ln248_5_fu_1787_p2 = (6'd0 - zext_ln248_4_reg_3290);

assign sub_ln248_6_fu_1695_p2 = (10'd0 - tmp_12_fu_1688_p3);

assign sub_ln248_7_fu_1858_p2 = (6'd0 - zext_ln248_6_reg_3312);

assign sub_ln248_8_fu_1545_p2 = (32'd0 - word_1_q1);

assign sub_ln248_9_fu_1766_p2 = (10'd0 - tmp_16_fu_1759_p3);

assign sub_ln248_fu_1489_p2 = (32'd0 - word_1_q0);

assign temp_0_0_fu_1898_p2 = (Sbox_q0 ^ Rcon0_q0);

assign tmp_10_fu_1629_p4 = {{word_1_load_8_reg_3229[9:4]}};

assign tmp_12_fu_1688_p3 = {{6'd0}, {trunc_ln248_3_reg_3263}};

assign tmp_13_fu_1701_p3 = {{6'd0}, {trunc_ln248_2_fu_1685_p1}};

assign tmp_14_fu_1721_p4 = {{word_0_load_7_reg_3251[9:4]}};

assign tmp_16_fu_1759_p3 = {{6'd0}, {trunc_ln248_5_reg_3285}};

assign tmp_17_fu_1772_p3 = {{6'd0}, {trunc_ln248_4_fu_1756_p1}};

assign tmp_18_fu_1792_p4 = {{word_1_load_9_reg_3273[9:4]}};

assign tmp_20_fu_1830_p3 = {{6'd0}, {trunc_ln248_7_reg_3307}};

assign tmp_21_fu_1843_p3 = {{6'd0}, {trunc_ln248_6_fu_1827_p1}};

assign tmp_22_fu_1863_p4 = {{word_0_load_8_reg_3295[9:4]}};

assign tmp_23_fu_2277_p3 = {{n_assign_reg_1182}, {2'd0}};

assign tmp_24_fu_1960_p3 = {{lshr_ln1_fu_1950_p4}, {7'd0}};

assign tmp_25_fu_1968_p3 = {{lshr_ln1_fu_1950_p4}, {3'd0}};

assign tmp_26_fu_2002_p3 = i_2_i_reg_1160[32'd1];

assign tmp_27_fu_2362_p4 = {{statemt_0_q0[30:7]}};

assign tmp_28_fu_2412_p4 = {{x_1_fu_2406_p2[31:8]}};

assign tmp_29_fu_2474_p4 = {{statemt_1_q0[30:7]}};

assign tmp_30_fu_2524_p4 = {{x_3_fu_2518_p2[31:8]}};

assign tmp_31_fu_2586_p4 = {{statemt_0_q1[30:7]}};

assign tmp_32_fu_2636_p4 = {{x_5_fu_2630_p2[31:8]}};

assign tmp_33_fu_2698_p4 = {{statemt_1_q1[30:7]}};

assign tmp_34_fu_2742_p4 = {{x_7_fu_2736_p2[31:8]}};

assign tmp_3_fu_1407_p4 = {{sub_ln142_fu_1391_p2[9:3]}};

assign tmp_4_fu_1367_p3 = {{lshr_ln_fu_1357_p4}, {7'd0}};

assign tmp_5_fu_1379_p3 = {{lshr_ln_fu_1357_p4}, {3'd0}};

assign tmp_6_fu_1417_p3 = {{tmp_3_fu_1407_p4}, {or_ln142_fu_1401_p2}};

assign tmp_8_fu_1596_p3 = {{6'd0}, {trunc_ln248_1_reg_3241}};

assign tmp_9_fu_1609_p3 = {{6'd0}, {trunc_ln248_fu_1593_p1}};

assign tmp_s_fu_2077_p3 = {{61'd15}, {j_0_i7_reg_1171}};

assign trunc_ln141_fu_3105_p1 = i_2_reg_1227[0:0];

assign trunc_ln142_1_fu_1353_p1 = i_0_i_reg_1096[0:0];

assign trunc_ln142_2_fu_1397_p1 = sub_ln142_fu_1391_p2[2:0];

assign trunc_ln142_fu_1315_p1 = j_0_i_reg_1084[1:0];

assign trunc_ln146_fu_1437_p1 = j_1_i_reg_1108[1:0];

assign trunc_ln154_1_fu_1664_p4 = {{j_1_i_reg_1108[5:2]}};

assign trunc_ln173_fu_1946_p1 = i_2_i_reg_1160[0:0];

assign trunc_ln248_1_fu_1495_p1 = sub_ln248_fu_1489_p2[3:0];

assign trunc_ln248_2_fu_1685_p1 = word_0_load_7_reg_3251[3:0];

assign trunc_ln248_3_fu_1523_p1 = sub_ln248_4_fu_1517_p2[3:0];

assign trunc_ln248_4_fu_1756_p1 = word_1_load_9_reg_3273[3:0];

assign trunc_ln248_5_fu_1551_p1 = sub_ln248_8_fu_1545_p2[3:0];

assign trunc_ln248_6_fu_1827_p1 = word_0_load_8_reg_3295[3:0];

assign trunc_ln248_7_fu_1579_p1 = sub_ln248_10_fu_1573_p2[3:0];

assign trunc_ln248_fu_1593_p1 = word_1_load_8_reg_3229[3:0];

assign trunc_ln393_fu_2340_p1 = add_ln393_fu_2329_p2[8:0];

assign x_1_fu_2406_p2 = (statemt_1_q0 ^ shl_ln388_fu_2400_p2);

assign x_3_fu_2518_p2 = (statemt_0_q1 ^ shl_ln400_fu_2512_p2);

assign x_5_fu_2630_p2 = (statemt_1_q1 ^ shl_ln412_fu_2624_p2);

assign x_7_fu_2736_p2 = (statemt_0_q0 ^ shl_ln384_1_fu_2356_p2);

assign xor_ln173_fu_2052_p2 = (select_ln173_3_reg_3400 ^ select_ln173_2_fu_2045_p3);

assign xor_ln386_fu_2386_p2 = (shl_ln384_1_fu_2356_p2 ^ 32'd283);

assign xor_ln390_fu_2436_p2 = (x_1_fu_2406_p2 ^ 32'd283);

assign xor_ln393_1_fu_2456_p2 = (select_ln389_fu_2442_p3 ^ select_ln385_fu_2392_p3);

assign xor_ln393_2_fu_2468_p2 = (xor_ln393_fu_2450_p2 ^ xor_ln393_3_fu_2462_p2);

assign xor_ln393_3_fu_2462_p2 = (xor_ln393_1_fu_2456_p2 ^ word_0_q1);

assign xor_ln393_fu_2450_p2 = (statemt_1_q1 ^ statemt_0_q1);

assign xor_ln398_fu_2498_p2 = (shl_ln388_fu_2400_p2 ^ 32'd283);

assign xor_ln402_fu_2548_p2 = (x_3_fu_2518_p2 ^ 32'd283);

assign xor_ln405_1_fu_2568_p2 = (select_ln401_fu_2554_p3 ^ select_ln397_fu_2504_p3);

assign xor_ln405_2_fu_2580_p2 = (xor_ln405_fu_2562_p2 ^ xor_ln405_3_fu_2574_p2);

assign xor_ln405_3_fu_2574_p2 = (xor_ln405_1_fu_2568_p2 ^ word_1_q1);

assign xor_ln405_fu_2562_p2 = (statemt_1_q1 ^ statemt_0_q0);

assign xor_ln410_fu_2610_p2 = (shl_ln400_fu_2512_p2 ^ 32'd283);

assign xor_ln414_fu_2660_p2 = (x_5_fu_2630_p2 ^ 32'd283);

assign xor_ln417_1_fu_2680_p2 = (select_ln413_fu_2666_p3 ^ select_ln409_fu_2616_p3);

assign xor_ln417_2_fu_2692_p2 = (xor_ln417_fu_2674_p2 ^ xor_ln417_3_fu_2686_p2);

assign xor_ln417_3_fu_2686_p2 = (xor_ln417_1_fu_2680_p2 ^ word_0_q0);

assign xor_ln417_fu_2674_p2 = (statemt_1_q0 ^ statemt_0_q0);

assign xor_ln422_fu_2722_p2 = (shl_ln412_fu_2624_p2 ^ 32'd283);

assign xor_ln426_fu_2766_p2 = (x_7_fu_2736_p2 ^ 32'd283);

assign xor_ln429_1_fu_2786_p2 = (select_ln425_fu_2772_p3 ^ select_ln421_fu_2728_p3);

assign xor_ln429_2_fu_2798_p2 = (xor_ln429_fu_2780_p2 ^ xor_ln429_3_fu_2792_p2);

assign xor_ln429_3_fu_2792_p2 = (xor_ln429_1_fu_2786_p2 ^ word_1_q0);

assign xor_ln429_fu_2780_p2 = (statemt_1_q0 ^ statemt_0_q1);

assign zext_ln140_1_fu_2217_p1 = reg_1267;

assign zext_ln140_fu_2946_p1 = reg_1267;

assign zext_ln141_1_fu_3099_p1 = lshr_ln141_2_fu_3089_p4;

assign zext_ln141_2_fu_3127_p1 = icmp_ln141_fu_3121_p2;

assign zext_ln141_3_fu_3117_p1 = out_enc_statemt_q0;

assign zext_ln141_4_fu_2906_p1 = reg_1271;

assign zext_ln141_5_fu_2177_p1 = reg_1271;

assign zext_ln141_fu_3084_p1 = i_2_reg_1227;

assign zext_ln142_1_fu_1348_p1 = add_ln142_fu_1343_p2;

assign zext_ln142_2_fu_1375_p1 = tmp_4_fu_1367_p3;

assign zext_ln142_3_fu_1387_p1 = tmp_5_fu_1379_p3;

assign zext_ln142_4_fu_2911_p1 = reg_1286;

assign zext_ln142_5_fu_2182_p1 = reg_1286;

assign zext_ln142_fu_1339_p1 = i_0_i_reg_1096;

assign zext_ln143_1_fu_2222_p1 = reg_1291;

assign zext_ln143_fu_2951_p1 = reg_1291;

assign zext_ln146_1_fu_2187_p1 = reg_1276;

assign zext_ln146_fu_2916_p1 = reg_1276;

assign zext_ln147_1_fu_2192_p1 = reg_1281;

assign zext_ln147_fu_2921_p1 = reg_1281;

assign zext_ln149_1_fu_2227_p1 = reg_1295;

assign zext_ln149_fu_2956_p1 = reg_1295;

assign zext_ln150_1_fu_2232_p1 = reg_1299;

assign zext_ln150_fu_2961_p1 = reg_1299;

assign zext_ln153_1_fu_2257_p1 = reg_1271;

assign zext_ln153_fu_2986_p1 = reg_1271;

assign zext_ln154_1_fu_1680_p1 = add_ln154_1_fu_1674_p2;

assign zext_ln154_2_fu_1904_p1 = temp_0_0_fu_1898_p2;

assign zext_ln154_3_fu_2966_p1 = reg_1276;

assign zext_ln154_4_fu_2237_p1 = reg_1276;

assign zext_ln154_fu_1453_p1 = add_ln154_fu_1447_p2;

assign zext_ln155_1_fu_1469_p1 = add_ln155_fu_1463_p2;

assign zext_ln155_2_fu_2971_p1 = reg_1267;

assign zext_ln155_3_fu_2242_p1 = reg_1267;

assign zext_ln155_fu_1459_p1 = add_ln154_fu_1447_p2;

assign zext_ln156_1_fu_2262_p1 = reg_1291;

assign zext_ln156_fu_2991_p1 = reg_1291;

assign zext_ln159_1_fu_2247_p1 = reg_1281;

assign zext_ln159_fu_2976_p1 = reg_1281;

assign zext_ln160_1_fu_2252_p1 = reg_1286;

assign zext_ln160_fu_2981_p1 = reg_1286;

assign zext_ln161_1_fu_2267_p1 = reg_1295;

assign zext_ln161_fu_2996_p1 = reg_1295;

assign zext_ln162_1_fu_2272_p1 = reg_1299;

assign zext_ln162_fu_3001_p1 = reg_1299;

assign zext_ln172_fu_1930_p1 = j_1_i_reg_1108;

assign zext_ln173_1_fu_1976_p1 = tmp_25_fu_1968_p3;

assign zext_ln173_fu_1926_p1 = add_ln173_fu_1920_p2;

assign zext_ln248_1_fu_1912_p1 = Sbox_q2;

assign zext_ln248_3_fu_1916_p1 = Sbox_q3;

assign zext_ln248_fu_1908_p1 = Sbox_q1;

assign zext_ln384_fu_2311_p1 = shl_ln384_fu_2305_p2;

assign zext_ln393_1_fu_2334_p1 = add_ln393_fu_2329_p2;

assign zext_ln393_2_fu_2285_p1 = tmp_23_fu_2277_p3;

assign zext_ln393_fu_2323_p1 = or_ln393_fu_2317_p2;

assign zext_ln417_fu_2350_p1 = add_ln417_fu_2344_p2;

assign zext_ln437_fu_2822_p1 = shl_ln437_fu_2816_p2;

assign zext_ln439_fu_2834_p1 = or_ln439_fu_2828_p2;

assign zext_ln570_1_fu_2093_p1 = shl_ln570_fu_2087_p2;

assign zext_ln570_2_fu_3054_p1 = shl_ln570_1_fu_3048_p2;

assign zext_ln570_3_fu_3026_p1 = or_ln_fu_3018_p3;

assign zext_ln570_4_fu_3032_p1 = or_ln_fu_3018_p3;

assign zext_ln570_fu_2071_p1 = j_0_i7_reg_1171;

assign zext_ln572_1_fu_3066_p1 = or_ln572_1_fu_3060_p2;

assign zext_ln572_2_fu_3042_p1 = add_ln572_fu_3036_p2;

assign zext_ln572_fu_2105_p1 = or_ln572_fu_2099_p2;

always @ (posedge ap_clk) begin
    shl_ln_reg_3160[1:0] <= 2'b00;
    zext_ln173_reg_3362[8:6] <= 3'b000;
    zext_ln172_reg_3367[8:6] <= 3'b000;
    statemt_0_addr_reg_3438[0] <= 1'b0;
    statemt_0_addr_reg_3438[3] <= 1'b0;
    statemt_1_addr_reg_3443[0] <= 1'b0;
    statemt_1_addr_reg_3443[3] <= 1'b0;
    statemt_0_addr_1_reg_3448[0] <= 1'b1;
    statemt_0_addr_1_reg_3448[3] <= 1'b0;
    statemt_1_addr_1_reg_3453[0] <= 1'b1;
    statemt_1_addr_1_reg_3453[3] <= 1'b0;
    zext_ln393_2_reg_3616[1:0] <= 2'b00;
    zext_ln393_2_reg_3616[31:6] <= 26'b00000000000000000000000000;
    zext_ln384_reg_3629[0] <= 1'b0;
    zext_ln384_reg_3629[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln393_reg_3645[0] <= 1'b1;
    zext_ln393_reg_3645[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln437_reg_3709[0] <= 1'b0;
    zext_ln437_reg_3709[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln439_reg_3725[0] <= 1'b1;
    zext_ln439_reg_3725[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    statemt_0_addr_10_reg_3854[0] <= 1'b0;
    statemt_0_addr_10_reg_3854[3] <= 1'b0;
    statemt_1_addr_10_reg_3859[0] <= 1'b0;
    statemt_1_addr_10_reg_3859[3] <= 1'b0;
    statemt_0_addr_11_reg_3864[0] <= 1'b1;
    statemt_0_addr_11_reg_3864[3] <= 1'b0;
    statemt_1_addr_11_reg_3869[0] <= 1'b1;
    statemt_1_addr_11_reg_3869[3] <= 1'b0;
end

endmodule //encrypt
